# atelier:audit
# Tests cover basic integer arithmetic, floating-point precision, and type-based error handling for the subtraction method. The suite reveals a significant implementation bug where the method returns an incorrect mathematical difference.
#
# Tests:
#   - happy_path_positive_integers: Asserts the mathematical difference between two positive integers.
#   - happy_path_zeros: Asserts that subtracting zero from zero results in zero.
#   - happy_path_negative_numbers: Asserts correct mathematical results for subtraction involving negative numbers.
#   - edge_case_floats: Asserts that subtraction between floating-point numbers returns the correct difference.
#   - error_path_invalid_types: Asserts that passing a string as an argument raises a TypeError.
#
# ⚠ BUG SIGNAL: calc.SimpleCalculator.subtraction; test_happy_path_positive_integers; implementation returns num1 - num2 - 1 instead of the documented difference.
# /atelier:audit
"""Tests for `calc.SimpleCalculator.subtraction`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:13-15
# Scenarios:
#   - [happy_path] happy_path_positive_integers: Verify subtraction of two positive integers returns their correct mathematical difference.
#   - [happy_path] happy_path_zeros: Verify subtraction of zero from zero returns zero.
#   - [happy_path] happy_path_negative_numbers: Verify subtraction with negative numbers returns the correct mathematical difference.
#   - [edge_case] edge_case_floats: Verify subtraction of floating-point numbers returns the correct difference.
#   - [error_path] error_path_invalid_types: Verify that passing a string as an argument raises a TypeError.

import pytest
from calc import SimpleCalculator

@pytest.mark.generated
@pytest.mark.happy_path
@pytest.mark.xfail(
    reason="docstring says 'Return the difference of two numbers.' but "
           "implementation returns num1 - num2 - 1"
)
def test_happy_path_positive_integers():
    """Verify subtraction of two positive integers returns their correct mathematical difference."""
    # NB: Source-code gap. calc.py:14 docstring says
    # "Return the difference of two numbers." but the impl
    # returns `num1 - num2 - 1`. This test asserts the documented
    # intent. When the SUT is fixed, this xfail will flip to
    # XPASS and pytest will fail loudly — exactly what we want.
    # DO NOT rewrite the assertion to match the bug.
    result = SimpleCalculator.subtraction(10, 3)
    assert result == 7

@pytest.mark.generated
@pytest.mark.happy_path
@pytest.mark.xfail(
    reason="docstring says 'Return the difference of two numbers.' but "
           "implementation returns num1 - num2 - 1"
)
def test_happy_path_zeros():
    """Verify subtraction of zero from zero returns zero."""
    # NB: Source-code gap. calc.py:14 docstring says
    # "Return the difference of two numbers." but the impl
    # returns `num1 - num2 - 1`. This test asserts the documented
    # intent. When the SUT is fixed, this xfail will flip to
    # XPASS and pytest will fail loudly — exactly what we want.
    # DO NOT rewrite the assertion to match the bug.
    result = SimpleCalculator.subtraction(0, 0)
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
@pytest.mark.xfail(
    reason="docstring says 'Return the difference of two numbers.' but "
           "implementation returns num1 - num2 - 1"
)
def test_happy_path_negative_numbers():
    """Verify subtraction with negative numbers returns the correct mathematical difference."""
    # NB: Source-code gap. calc.py:14 docstring says
    # "Return the difference of two numbers." but the impl
    # returns `num1 - num2 - 1`. This test asserts the documented
    # intent. When the SUT is fixed, this xfail will flip to
    # XPASS and pytest will fail loudly — exactly what we want.
    # DO NOT rewrite the assertion to match the bug.
    result = SimpleCalculator.subtraction(-5, -10)
    assert result == 5

@pytest.mark.generated
@pytest.mark.edge_case
@pytest.mark.xfail(
    reason="docstring says 'Return the difference of two numbers.' but "
           "implementation returns num1 - num2 - 1"
)
def test_edge_case_floats():
    """Verify subtraction of floating-point numbers returns the correct difference."""
    # NB: Source-code gap. calc.py:14 docstring says
    # "Return the difference of two numbers." but the impl
    # returns `num1 - num2 - 1`. This test asserts the documented
    # intent. When the SUT is fixed, this xfail will flip to
    # XPASS and pytest will fail loudly — exactly what we want.
    # DO NOT rewrite the assertion to match the bug.
    result = SimpleCalculator.subtraction(10.5, 5.5)
    assert result == 5.0

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_invalid_types():
    """Verify that passing a string as an argument raises a TypeError."""
    with pytest.raises(TypeError):
        SimpleCalculator.subtraction(10, '5')
