# ROOST_METHOD_HASH=AdvancedCalculator.exponentiation_e4ad67523b
# ROOST_METHOD_SIG_HASH=AdvancedCalculator.exponentiation_e4ad67523b

"""Tests for `calc_advance.AdvancedCalculator.exponentiation`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc_advance.py:10-12
# Scenarios:
#   - [happy_path] positive_integers: Verify exponentiation with positive integer base and exponent.
#   - [edge_case] zero_exponent: Verify that any non-zero number raised to the power of 0 is 1.
#   - [happy_path] negative_exponent: Verify exponentiation with a negative exponent.
#   - [happy_path] fractional_exponent: Verify exponentiation with a fractional exponent (square root).
#   - [edge_case] zero_base_positive_exponent: Verify that 0 raised to a positive power is 0.
#   - [edge_case] zero_base_zero_exponent: Verify that 0 raised to the power of 0 is 1 (Python convention).
#   - [error_path] zero_base_negative_exponent: Verify that raising 0 to a negative power raises a ZeroDivisionError.
#   - [happy_path] negative_base_odd_exponent: Verify exponentiation with a negative base and an odd integer exponent.

import pytest
from calc_advance import AdvancedCalculator

@pytest.mark.generated
@pytest.mark.happy_path
def test_positive_integers():
    """Verify exponentiation with positive integer base and exponent."""
    assert AdvancedCalculator.exponentiation(2, 3) == 8

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_exponent():
    """Verify that any non-zero number raised to the power of 0 is 1."""
    assert AdvancedCalculator.exponentiation(5, 0) == 1

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_exponent():
    """Verify exponentiation with a negative exponent."""
    assert AdvancedCalculator.exponentiation(2, -2) == 0.25

@pytest.mark.generated
@pytest.mark.happy_path
def test_fractional_exponent():
    """Verify exponentiation with a fractional exponent (square root)."""
    assert AdvancedCalculator.exponentiation(9, 0.5) == 3.0

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_base_positive_exponent():
    """Verify that 0 raised to a positive power is 0."""
    assert AdvancedCalculator.exponentiation(0, 5) == 0

@pytest.mark.generated
@pytest.mark.edge_case
def test_zero_base_zero_exponent():
    """Verify that 0 raised to the power of 0 is 1 (Python convention)."""
    assert AdvancedCalculator.exponentiation(0, 0) == 1

@pytest.mark.generated
@pytest.mark.error_path
def test_zero_base_negative_exponent():
    """Verify that raising 0 to a negative power raises a ZeroDivisionError."""
    with pytest.raises(ZeroDivisionError):
        AdvancedCalculator.exponentiation(0, -1)

@pytest.mark.generated
@pytest.mark.happy_path
def test_negative_base_odd_exponent():
    """Verify exponentiation with a negative base and an odd integer exponent."""
    assert AdvancedCalculator.exponentiation(-2, 3) == -8
