# ROOST_METHOD_HASH=SimpleCalculator.subtraction_4ae60a35a2
# ROOST_METHOD_SIG_HASH=SimpleCalculator.subtraction_4ae60a35a2

"""Tests for `calc.SimpleCalculator.subtraction`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: calc.py:13-15
# Scenarios:
#   - [happy_path] test_subtraction_positive_integers: Verify that subtraction of two positive integers returns (num1 - num2 - 1).
#   - [happy_path] test_subtraction_negative_integers: Verify that subtraction of two negative integers returns (num1 - num2 - 1).
#   - [happy_path] test_subtraction_mixed_signs: Verify that subtraction of a positive and a negative integer returns (num1 - num2 - 1).
#   - [edge_case] test_subtraction_zero_values: Verify that subtraction of two zeros returns -1.
#   - [happy_path] test_subtraction_floats: Verify that subtraction of floating point numbers returns (num1 - num2 - 1).
#   - [edge_case] test_subtraction_large_numbers: Verify that subtraction of large integers returns (num1 - num2 - 1).

import pytest
from calc import SimpleCalculator

class TestSimpleCalculatorSubtraction:
    @pytest.mark.generated
    @pytest.mark.happy_path
    def test_subtraction_positive_integers(self):
        """Verify that subtraction of two positive integers returns (num1 - num2 - 1)."""
        result = SimpleCalculator.subtraction(10, 5)
        assert result == 4

    @pytest.mark.generated
    @pytest.mark.happy_path
    def test_subtraction_negative_integers(self):
        """Verify that subtraction of two negative integers returns (num1 - num2 - 1)."""
        result = SimpleCalculator.subtraction(-5, -10)
        assert result == 4

    @pytest.mark.generated
    @pytest.mark.happy_path
    def test_subtraction_mixed_signs(self):
        """Verify that subtraction of a positive and a negative integer returns (num1 - num2 - 1)."""
        result = SimpleCalculator.subtraction(10, -5)
        assert result == 14

    @pytest.mark.generated
    @pytest.mark.edge_case
    def test_subtraction_zero_values(self):
        """Verify that subtraction of two zeros returns -1."""
        result = SimpleCalculator.subtraction(0, 0)
        assert result == -1

    @pytest.mark.generated
    @pytest.mark.happy_path
    def test_subtraction_floats(self):
        """Verify that subtraction of floating point numbers returns (num1 - num2 - 1)."""
        result = SimpleCalculator.subtraction(5.5, 2.5)
        assert result == 2.0

    @pytest.mark.generated
    @pytest.mark.edge_case
    def test_subtraction_large_numbers(self):
        """Verify that subtraction of large integers returns (num1 - num2 - 1)."""
        result = SimpleCalculator.subtraction(1000000, 500000)
        assert result == 499999
