openapi: 3.0.0
info:
  title: Mobile Banking Application for Bank Leumi
  version: 1.1.0
  description: API for managing mobile banking services for Bank Leumi customers.
servers:
  - url: https://api.leumi.com
    description: Production server
paths:
  /login:
    post:
      summary: User Login with Valid Credentials
      description: Authenticate user with valid credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identityNumber:
                  type: string
                  example: "123456789"
                otp:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid credentials"
  /account-details:
    get:
      summary: View Account Details
      description: Retrieve account details for the authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful retrieval of account details
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    example: 1500.75
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          example: "2023-10-01"
                        type:
                          type: string
                          example: "debit"
                        amount:
                          type: number
                          example: 50.00
                  accountNumber:
                    type: string
                    example: "1234567890"
                  branchId:
                    type: string
                    example: "0123"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid token"
  /transfer:
    post:
      summary: Transfer Funds
      description: Transfer funds to an internal or external account.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                toAccount:
                  type: string
                  example: "9876543210"
                amount:
                  type: number
                  example: 100.00
                scheduledDate:
                  type: string
                  format: date
                  example: "2023-10-15"
      responses:
        '200':
          description: Successful transfer
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transfer successful"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid token"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Insufficient funds"
  /credit-card:
    get:
      summary: View Credit Card Details
      description: Retrieve details of the user's credit card.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful retrieval of credit card details
          content:
            application/json:
              schema:
                type: object
                properties:
                  availableBalance:
                    type: number
                    example: 5000.00
                  futureCharges:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          example: "2023-10-10"
                        amount:
                          type: number
                          example: 200.00
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid token"
  /loan:
    post:
      summary: Apply for a Loan
      description: Apply for a loan and get a simulation of the monthly repayment.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 10000.00
                term:
                  type: integer
                  example: 12
      responses:
        '200':
          description: Successful loan application
          content:
            application/json:
              schema:
                type: object
                properties:
                  monthlyRepayment:
                    type: number
                    example: 875.00
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid token"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid loan amount or term"
  /customer-service:
    post:
      summary: Create a Customer Service Ticket
      description: Create a new customer service ticket.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                issue:
                  type: string
                  example: "Unable to access account"
      responses:
        '200':
          description: Successful ticket creation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticketId:
                    type: string
                    example: "TICKET12345"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid token"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
